# src/modules/analysis/application/dtos/analysis_dtos.py
from dataclasses import dataclass
from typing import Dict, Any, Optional, List
from src.shared.configs.exceptions.exceptions import ValidationException


# ============================================================================
# CRIME ANALYSIS DTOs
# ============================================================================

@dataclass
class CreateCrimeAnalysisRequest:
    """DTO for creating a crime analysis."""
    analysis_period_start: str  # ISO format datetime
    analysis_period_end: str  # ISO format datetime
    generated_by: str

    def __post_init__(self):
        """Validate analysis data."""
        if not self.analysis_period_start:
            raise ValidationException("Analysis period start date is required")
        if not self.analysis_period_end:
            raise ValidationException("Analysis period end date is required")
        if not self.generated_by:
            raise ValidationException("Generated by user ID is required")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'analysis_period_start': self.analysis_period_start,
            'analysis_period_end': self.analysis_period_end,
            'generated_by': self.generated_by
        }


@dataclass
class CrimeAnalysisResponse:
    """DTO for crime analysis response."""
    id: str
    analysis_period_start: str
    analysis_period_end: str
    total_crimes: int
    total_missing_persons: int
    summary: str
    generated_by: str
    created_at: str
    updated_at: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'id': self.id,
            'analysis_period_start': self.analysis_period_start,
            'analysis_period_end': self.analysis_period_end,
            'total_crimes': self.total_crimes,
            'total_missing_persons': self.total_missing_persons,
            'summary': self.summary,
            'generated_by': self.generated_by,
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }


@dataclass
class ListCrimeAnalysesRequest:
    """DTO for listing crime analyses with filters."""
    page: int = 1
    per_page: int = 20
    generated_by: Optional[str] = None
    start_date: Optional[str] = None  # Filter by analysis period start
    end_date: Optional[str] = None  # Filter by analysis period end
    include_deleted: bool = False

    def __post_init__(self):
        """Validate pagination parameters."""
        if self.page < 1:
            raise ValidationException("Page must be at least 1")
        if self.per_page < 1 or self.per_page > 100:
            raise ValidationException("Per page must be between 1 and 100")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {
            'page': self.page,
            'per_page': self.per_page,
            'include_deleted': self.include_deleted
        }
        if self.generated_by is not None:
            data['generated_by'] = self.generated_by
        if self.start_date is not None:
            data['start_date'] = self.start_date
        if self.end_date is not None:
            data['end_date'] = self.end_date
        return data


@dataclass
class ListCrimeAnalysesResponse:
    """DTO for list crime analyses response."""
    message: str
    analyses: List[Dict[str, Any]]
    total: int
    page: int
    per_page: int
    total_pages: int

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'message': self.message,
            'analyses': self.analyses,
            'pagination': {
                'total': self.total,
                'page': self.page,
                'per_page': self.per_page,
                'total_pages': self.total_pages
            }
        }


# ============================================================================
# CRIME HOTSPOT DTOs
# ============================================================================

@dataclass
class CreateCrimeHotspotRequest:
    """DTO for creating a crime hotspot."""
    location_id: str
    analysis_id: str
    incident_count: int
    risk_level: str  # RiskLevel enum value
    crime_type: Optional[str] = None
    is_missing_person_hotspot: bool = False

    def __post_init__(self):
        """Validate hotspot data."""
        if not self.location_id:
            raise ValidationException("Location ID is required")
        if not self.analysis_id:
            raise ValidationException("Analysis ID is required")
        if self.incident_count < 0:
            raise ValidationException("Incident count cannot be negative")
        if not self.risk_level:
            raise ValidationException("Risk level is required")

        valid_risk_levels = ['low', 'medium', 'high', 'critical']
        if self.risk_level not in valid_risk_levels:
            raise ValidationException(f"Invalid risk level: {self.risk_level}. Must be one of: {', '.join(valid_risk_levels)}")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'location_id': self.location_id,
            'analysis_id': self.analysis_id,
            'incident_count': self.incident_count,
            'crime_type': self.crime_type,
            'is_missing_person_hotspot': self.is_missing_person_hotspot,
            'risk_level': self.risk_level
        }


@dataclass
class UpdateCrimeHotspotRequest:
    """DTO for updating crime hotspot details."""
    hotspot_id: str
    incident_count: Optional[int] = None
    risk_level: Optional[str] = None
    crime_type: Optional[str] = None

    def __post_init__(self):
        """Validate update data."""
        if not self.hotspot_id:
            raise ValidationException("Hotspot ID is required")
        if self.incident_count is not None and self.incident_count < 0:
            raise ValidationException("Incident count cannot be negative")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {'hotspot_id': self.hotspot_id}
        if self.incident_count is not None:
            data['incident_count'] = self.incident_count
        if self.risk_level is not None:
            data['risk_level'] = self.risk_level
        if self.crime_type is not None:
            data['crime_type'] = self.crime_type
        return data


@dataclass
class CrimeHotspotResponse:
    """DTO for crime hotspot response."""
    id: str
    location_id: str
    analysis_id: str
    incident_count: int
    crime_type: Optional[str]
    is_missing_person_hotspot: bool
    risk_level: str
    location: Optional[Dict[str, Any]]
    created_at: str
    updated_at: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'id': self.id,
            'location_id': self.location_id,
            'analysis_id': self.analysis_id,
            'incident_count': self.incident_count,
            'crime_type': self.crime_type,
            'is_missing_person_hotspot': self.is_missing_person_hotspot,
            'risk_level': self.risk_level,
            'location': self.location,
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }


@dataclass
class ListCrimeHotspotsRequest:
    """DTO for listing crime hotspots with filters."""
    page: int = 1
    per_page: int = 20
    analysis_id: Optional[str] = None
    location_id: Optional[str] = None
    risk_level: Optional[str] = None
    crime_type: Optional[str] = None
    is_missing_person_hotspot: Optional[bool] = None
    include_deleted: bool = False

    def __post_init__(self):
        """Validate pagination parameters."""
        if self.page < 1:
            raise ValidationException("Page must be at least 1")
        if self.per_page < 1 or self.per_page > 100:
            raise ValidationException("Per page must be between 1 and 100")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {
            'page': self.page,
            'per_page': self.per_page,
            'include_deleted': self.include_deleted
        }
        if self.analysis_id is not None:
            data['analysis_id'] = self.analysis_id
        if self.location_id is not None:
            data['location_id'] = self.location_id
        if self.risk_level is not None:
            data['risk_level'] = self.risk_level
        if self.crime_type is not None:
            data['crime_type'] = self.crime_type
        if self.is_missing_person_hotspot is not None:
            data['is_missing_person_hotspot'] = self.is_missing_person_hotspot
        return data


@dataclass
class ListCrimeHotspotsResponse:
    """DTO for list crime hotspots response."""
    message: str
    hotspots: List[Dict[str, Any]]
    total: int
    page: int
    per_page: int
    total_pages: int

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'message': self.message,
            'hotspots': self.hotspots,
            'pagination': {
                'total': self.total,
                'page': self.page,
                'per_page': self.per_page,
                'total_pages': self.total_pages
            }
        }


# ============================================================================
# CRIME TREND DTOs
# ============================================================================

@dataclass
class CreateCrimeTrendRequest:
    """DTO for creating a crime trend."""
    analysis_id: str
    trend_category: str  # TrendCategory enum value
    description: str
    severity: str  # SeverityLevel enum value
    hotspot_id: Optional[str] = None
    crime_type: Optional[str] = None
    affected_demographic: Optional[str] = None
    time_pattern: Optional[str] = None

    def __post_init__(self):
        """Validate trend data."""
        if not self.analysis_id:
            raise ValidationException("Analysis ID is required")
        if not self.trend_category:
            raise ValidationException("Trend category is required")
        if not self.description or not self.description.strip():
            raise ValidationException("Description is required")
        if not self.severity:
            raise ValidationException("Severity is required")

        valid_categories = ['crime', 'missing_person', 'combined']
        if self.trend_category not in valid_categories:
            raise ValidationException(f"Invalid trend category: {self.trend_category}. Must be one of: {', '.join(valid_categories)}")

        valid_severities = ['low', 'medium', 'high']
        if self.severity not in valid_severities:
            raise ValidationException(f"Invalid severity: {self.severity}. Must be one of: {', '.join(valid_severities)}")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'analysis_id': self.analysis_id,
            'hotspot_id': self.hotspot_id,
            'trend_category': self.trend_category,
            'crime_type': self.crime_type,
            'description': self.description,
            'affected_demographic': self.affected_demographic,
            'time_pattern': self.time_pattern,
            'severity': self.severity
        }


@dataclass
class UpdateCrimeTrendRequest:
    """DTO for updating crime trend details."""
    trend_id: str
    description: Optional[str] = None
    severity: Optional[str] = None
    affected_demographic: Optional[str] = None
    time_pattern: Optional[str] = None

    def __post_init__(self):
        """Validate update data."""
        if not self.trend_id:
            raise ValidationException("Trend ID is required")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {'trend_id': self.trend_id}
        if self.description is not None:
            data['description'] = self.description
        if self.severity is not None:
            data['severity'] = self.severity
        if self.affected_demographic is not None:
            data['affected_demographic'] = self.affected_demographic
        if self.time_pattern is not None:
            data['time_pattern'] = self.time_pattern
        return data


@dataclass
class CrimeTrendResponse:
    """DTO for crime trend response."""
    id: str
    analysis_id: str
    hotspot_id: Optional[str]
    trend_category: str
    crime_type: Optional[str]
    description: str
    affected_demographic: Optional[str]
    time_pattern: Optional[str]
    severity: str
    created_at: str
    updated_at: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'id': self.id,
            'analysis_id': self.analysis_id,
            'hotspot_id': self.hotspot_id,
            'trend_category': self.trend_category,
            'crime_type': self.crime_type,
            'description': self.description,
            'affected_demographic': self.affected_demographic,
            'time_pattern': self.time_pattern,
            'severity': self.severity,
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }


@dataclass
class ListCrimeTrendsRequest:
    """DTO for listing crime trends with filters."""
    page: int = 1
    per_page: int = 20
    analysis_id: Optional[str] = None
    hotspot_id: Optional[str] = None
    trend_category: Optional[str] = None
    severity: Optional[str] = None
    crime_type: Optional[str] = None
    include_deleted: bool = False

    def __post_init__(self):
        """Validate pagination parameters."""
        if self.page < 1:
            raise ValidationException("Page must be at least 1")
        if self.per_page < 1 or self.per_page > 100:
            raise ValidationException("Per page must be between 1 and 100")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {
            'page': self.page,
            'per_page': self.per_page,
            'include_deleted': self.include_deleted
        }
        if self.analysis_id is not None:
            data['analysis_id'] = self.analysis_id
        if self.hotspot_id is not None:
            data['hotspot_id'] = self.hotspot_id
        if self.trend_category is not None:
            data['trend_category'] = self.trend_category
        if self.severity is not None:
            data['severity'] = self.severity
        if self.crime_type is not None:
            data['crime_type'] = self.crime_type
        return data


@dataclass
class ListCrimeTrendsResponse:
    """DTO for list crime trends response."""
    message: str
    trends: List[Dict[str, Any]]
    total: int
    page: int
    per_page: int
    total_pages: int

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'message': self.message,
            'trends': self.trends,
            'pagination': {
                'total': self.total,
                'page': self.page,
                'per_page': self.per_page,
                'total_pages': self.total_pages
            }
        }


# ============================================================================
# RECOMMENDATION DTOs
# ============================================================================

@dataclass
class CreateRecommendationRequest:
    """DTO for creating a recommendation."""
    analysis_id: str
    recommendation_text: str
    priority: str  # PriorityLevel enum value
    hotspot_id: Optional[str] = None

    def __post_init__(self):
        """Validate recommendation data."""
        if not self.analysis_id:
            raise ValidationException("Analysis ID is required")
        if not self.recommendation_text or not self.recommendation_text.strip():
            raise ValidationException("Recommendation text is required")
        if not self.priority:
            raise ValidationException("Priority is required")

        valid_priorities = ['low', 'medium', 'high', 'urgent']
        if self.priority not in valid_priorities:
            raise ValidationException(f"Invalid priority: {self.priority}. Must be one of: {', '.join(valid_priorities)}")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'analysis_id': self.analysis_id,
            'hotspot_id': self.hotspot_id,
            'recommendation_text': self.recommendation_text,
            'priority': self.priority
        }


@dataclass
class UpdateRecommendationRequest:
    """DTO for updating recommendation details."""
    recommendation_id: str
    recommendation_text: Optional[str] = None
    priority: Optional[str] = None

    def __post_init__(self):
        """Validate update data."""
        if not self.recommendation_id:
            raise ValidationException("Recommendation ID is required")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {'recommendation_id': self.recommendation_id}
        if self.recommendation_text is not None:
            data['recommendation_text'] = self.recommendation_text
        if self.priority is not None:
            data['priority'] = self.priority
        return data


@dataclass
class RecommendationResponse:
    """DTO for recommendation response."""
    id: str
    analysis_id: str
    hotspot_id: Optional[str]
    recommendation_text: str
    priority: str
    created_at: str
    updated_at: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'id': self.id,
            'analysis_id': self.analysis_id,
            'hotspot_id': self.hotspot_id,
            'recommendation_text': self.recommendation_text,
            'priority': self.priority,
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }


@dataclass
class ListRecommendationsRequest:
    """DTO for listing recommendations with filters."""
    page: int = 1
    per_page: int = 20
    analysis_id: Optional[str] = None
    hotspot_id: Optional[str] = None
    priority: Optional[str] = None
    include_deleted: bool = False

    def __post_init__(self):
        """Validate pagination parameters."""
        if self.page < 1:
            raise ValidationException("Page must be at least 1")
        if self.per_page < 1 or self.per_page > 100:
            raise ValidationException("Per page must be between 1 and 100")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {
            'page': self.page,
            'per_page': self.per_page,
            'include_deleted': self.include_deleted
        }
        if self.analysis_id is not None:
            data['analysis_id'] = self.analysis_id
        if self.hotspot_id is not None:
            data['hotspot_id'] = self.hotspot_id
        if self.priority is not None:
            data['priority'] = self.priority
        return data


@dataclass
class ListRecommendationsResponse:
    """DTO for list recommendations response."""
    message: str
    recommendations: List[Dict[str, Any]]
    total: int
    page: int
    per_page: int
    total_pages: int

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'message': self.message,
            'recommendations': self.recommendations,
            'pagination': {
                'total': self.total,
                'page': self.page,
                'per_page': self.per_page,
                'total_pages': self.total_pages
            }
        }


# ============================================================================
# ALERT BROADCAST DTOs
# ============================================================================

@dataclass
class CreateAlertBroadcastRequest:
    """DTO for creating an alert broadcast."""
    hotspot_id: str
    message: str
    recipient_count: int = 0

    def __post_init__(self):
        """Validate alert data."""
        if not self.hotspot_id:
            raise ValidationException("Hotspot ID is required")
        if not self.message or not self.message.strip():
            raise ValidationException("Message is required")
        if self.recipient_count < 0:
            raise ValidationException("Recipient count cannot be negative")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'hotspot_id': self.hotspot_id,
            'message': self.message,
            'recipient_count': self.recipient_count
        }


@dataclass
class UpdateAlertBroadcastRequest:
    """DTO for updating alert broadcast details."""
    alert_id: str
    status: Optional[str] = None
    sent_at: Optional[str] = None  # ISO format datetime
    recipient_count: Optional[int] = None

    def __post_init__(self):
        """Validate update data."""
        if not self.alert_id:
            raise ValidationException("Alert ID is required")
        if self.recipient_count is not None and self.recipient_count < 0:
            raise ValidationException("Recipient count cannot be negative")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {'alert_id': self.alert_id}
        if self.status is not None:
            data['status'] = self.status
        if self.sent_at is not None:
            data['sent_at'] = self.sent_at
        if self.recipient_count is not None:
            data['recipient_count'] = self.recipient_count
        return data


@dataclass
class AlertBroadcastResponse:
    """DTO for alert broadcast response."""
    id: str
    hotspot_id: str
    message: str
    sent_at: Optional[str]
    recipient_count: int
    status: str
    created_at: str
    updated_at: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'id': self.id,
            'hotspot_id': self.hotspot_id,
            'message': self.message,
            'sent_at': self.sent_at,
            'recipient_count': self.recipient_count,
            'status': self.status,
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }


@dataclass
class ListAlertBroadcastsRequest:
    """DTO for listing alert broadcasts with filters."""
    page: int = 1
    per_page: int = 20
    hotspot_id: Optional[str] = None
    status: Optional[str] = None
    include_deleted: bool = False

    def __post_init__(self):
        """Validate pagination parameters."""
        if self.page < 1:
            raise ValidationException("Page must be at least 1")
        if self.per_page < 1 or self.per_page > 100:
            raise ValidationException("Per page must be between 1 and 100")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {
            'page': self.page,
            'per_page': self.per_page,
            'include_deleted': self.include_deleted
        }
        if self.hotspot_id is not None:
            data['hotspot_id'] = self.hotspot_id
        if self.status is not None:
            data['status'] = self.status
        return data


@dataclass
class ListAlertBroadcastsResponse:
    """DTO for list alert broadcasts response."""
    message: str
    alerts: List[Dict[str, Any]]
    total: int
    page: int
    per_page: int
    total_pages: int

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'message': self.message,
            'alerts': self.alerts,
            'pagination': {
                'total': self.total,
                'page': self.page,
                'per_page': self.per_page,
                'total_pages': self.total_pages
            }
        }


# ============================================================================
# ANALYSIS REPORT DTOs
# ============================================================================

@dataclass
class GenerateAnalysisReportRequest:
    """DTO for generating a complete analysis report."""
    start_date: str  # ISO format datetime
    end_date: str  # ISO format datetime
    generated_by: str
    radius_km: float = 2.0  # Clustering radius in kilometers (default: 2km)
    min_incidents: int = 3  # Minimum incidents to form a hotspot cluster
    include_hotspots: bool = True
    include_trends: bool = True
    include_recommendations: bool = True

    def __post_init__(self):
        """Validate report generation data."""
        if not self.start_date:
            raise ValidationException("Start date is required")
        if not self.end_date:
            raise ValidationException("End date is required")
        if not self.generated_by:
            raise ValidationException("Generated by user ID is required")
        if self.radius_km <= 0:
            raise ValidationException("Radius must be greater than 0")
        if self.radius_km > 10:
            raise ValidationException("Radius cannot exceed 10km for performance reasons")
        if self.min_incidents < 2:
            raise ValidationException("Minimum incidents must be at least 2")
        if self.min_incidents > 20:
            raise ValidationException("Minimum incidents cannot exceed 20")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'start_date': self.start_date,
            'end_date': self.end_date,
            'generated_by': self.generated_by,
            'radius_km': self.radius_km,
            'min_incidents': self.min_incidents,
            'include_hotspots': self.include_hotspots,
            'include_trends': self.include_trends,
            'include_recommendations': self.include_recommendations
        }


@dataclass
class AnalysisReportResponse:
    """DTO for complete analysis report response."""
    message: str
    analysis: Dict[str, Any]
    hotspots: List[Dict[str, Any]]
    trends: List[Dict[str, Any]]
    recommendations: List[Dict[str, Any]]

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'message': self.message,
            'analysis': self.analysis,
            'hotspots': self.hotspots,
            'trends': self.trends,
            'recommendations': self.recommendations
        }


# ============================================================================
# MAP VISUALIZATION DTOs
# ============================================================================

@dataclass
class GetMapDataRequest:
    """DTO for requesting map visualization data."""
    analysis_id: str
    include_crime_hotspots: bool = True
    include_missing_person_hotspots: bool = True
    min_risk_level: Optional[str] = None  # Filter by minimum risk level

    def __post_init__(self):
        """Validate map data request."""
        if not self.analysis_id:
            raise ValidationException("Analysis ID is required")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {
            'analysis_id': self.analysis_id,
            'include_crime_hotspots': self.include_crime_hotspots,
            'include_missing_person_hotspots': self.include_missing_person_hotspots
        }
        if self.min_risk_level is not None:
            data['min_risk_level'] = self.min_risk_level
        return data


@dataclass
class MapDataResponse:
    """DTO for map visualization data response."""
    message: str
    hotspots: List[Dict[str, Any]]  # Each with location coordinates and color coding
    analysis_period_start: str
    analysis_period_end: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'message': self.message,
            'hotspots': self.hotspots,
            'analysis_period': {
                'start': self.analysis_period_start,
                'end': self.analysis_period_end
            }
        }

@dataclass
class GetIndividualCrimeMapDataRequest:
    """DTO for requesting individual crime map data (tactical view)."""
    start_date: str  # ISO format datetime
    end_date: str  # ISO format datetime
    crime_types: Optional[List[str]] = None
    limit: Optional[int] = 1000

    def __post_init__(self):
        """Validate request parameters."""
        if not self.start_date:
            raise ValidationException("Start date is required")
        if not self.end_date:
            raise ValidationException("End date is required")
        if self.limit is not None and self.limit < 1:
            raise ValidationException("Limit must be at least 1")
        if self.limit is not None and self.limit > 5000:
            raise ValidationException("Limit cannot exceed 5000 for performance reasons")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = {
            'start_date': self.start_date,
            'end_date': self.end_date,
            'limit': self.limit
        }
        if self.crime_types is not None:
            data['crime_types'] = self.crime_types
        return data


@dataclass
class IndividualCrimeMapDataResponse:
    """DTO for individual crime map data response (tactical view)."""
    message: str
    crimes: List[Dict[str, Any]]
    total: int
    limited: bool
    period_start: str
    period_end: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'message': self.message,
            'crimes': self.crimes,
            'total': self.total,
            'limited': self.limited,
            'period': {
                'start': self.period_start,
                'end': self.period_end
            }
        }
# ============================================================================
# COMMON RESPONSE DTOs
# ============================================================================

@dataclass
class DeleteResponse:
    """Generic delete response DTO."""
    message: str
    id: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'message': self.message,
            'id': self.id
        }