# src/modules/analysis/data/repositories/crime_analysis_repository.py
from datetime import datetime
from typing import List, Optional

from src.modules.crime_analysis.domain.models.crime_analysis import CrimeAnalysis
from src.shared.data.base.repository import BaseRepository


class CrimeAnalysisRepository(BaseRepository[CrimeAnalysis]):
    """Repository for CrimeAnalysis model"""

    def __init__(self):
        super().__init__(CrimeAnalysis)

    def find_by_date_range(self, start_date: datetime, end_date: datetime) -> List[CrimeAnalysis]:
        """
        Find analyses that cover a specific date range.

        Args:
            start_date: Start date of the range
            end_date: End date of the range

        Returns:
            List of crime analyses within the date range
        """
        return self.model.query.filter(
            self.model.is_deleted == False,
            self.model.analysis_period_start >= start_date,
            self.model.analysis_period_end <= end_date
        ).order_by(self.model.analysis_period_start.desc()).all()

    def find_by_generated_by(self, user_id: str) -> List[CrimeAnalysis]:
        """Find all analyses generated by a specific user"""
        return self.find_many_by({"generated_by": user_id})

    def find_recent_analyses(self, limit: int = 10) -> List[CrimeAnalysis]:
        """
        Find most recent analyses.

        Args:
            limit: Number of recent analyses to return

        Returns:
            List of recent crime analyses
        """
        return self.model.query.filter(
            self.model.is_deleted == False
        ).order_by(self.model.created_at.desc()).limit(limit).all()

    def find_overlapping_period(self, start_date: datetime, end_date: datetime) -> List[CrimeAnalysis]:
        """
        Find analyses with overlapping time periods.

        Args:
            start_date: Start date to check
            end_date: End date to check

        Returns:
            List of analyses with overlapping periods
        """
        return self.model.query.filter(
            self.model.is_deleted == False,
            self.model.analysis_period_start <= end_date,
            self.model.analysis_period_end >= start_date
        ).all()